/* Static demo shim (generated by app/build_demo_site.py): answers the UI's API calls from recorded results. */
(() => {
  const realFetch = window.fetch.bind(window);
  const data = realFetch("demo/data.json").then((r) => r.json());
  const reply = (obj, status = 200) => new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json" } });
  const sha1 = async (blob) => [...new Uint8Array(await crypto.subtle.digest("SHA-1", await blob.arrayBuffer()))].map((b) => b.toString(16).padStart(2, "0")).join("");
  window.fetch = async (input, init) => {
    const url = typeof input === "string" ? input : input.url;
    if (url.startsWith("/api/info")) return reply((await data).info);
    if (url.startsWith("/api/samples")) return reply((await data).samples);
    if (url.startsWith("/api/search")) {
      const hit = (await data).results[await sha1(init.body.get("file"))];
      if (!hit) return reply({ detail: "This hosted demo only includes the six sample photos. To try your own photo, run the app locally (see the README)." }, 400);
      return reply(url.includes("extended=false") ? hit.base : hit.ext);
    }
    return realFetch(input, init);
  };
  addEventListener("DOMContentLoaded", () => {
    const n = document.createElement("div");
    n.setAttribute("role", "note");
    n.style.cssText = "font:500 13px/1.4 system-ui,sans-serif;padding:8px 16px;text-align:center;background:#111;color:#fff";
    n.innerHTML = 'Static demo: the six sample photos use results recorded from the real app. Your own photos need the backend: <a style="color:#fff" href="live.html">open the live app</a> (online only while its owner's computer is on). <a style="color:#fff" href="https://github.com/uplsiddharth-byte/Shop-the-Look-Visual-Product-Discovery">Source, setup and technical document</a>. Photos belong to their owners and are shown only to demonstrate the software.';
    document.body.prepend(n);
  });
})();
