"""Build a STATIC demo site (for GitHub Pages) from the running local server.

GitHub Pages can only host static files, so the models cannot run there. This script records the real answers of the live server
(http://localhost:8000) for the six sample photos, with and without the extended catalog, and packages the unchanged UI (web/) plus
a small shim (demo.js) that answers the UI's three API calls from the recorded data. Uploading any other photo needs the real backend.

Usage:  start the server (./run.sh), then   python app/build_demo_site.py [output_dir]      (default: site/, git-ignored)
Output: <out>/index.html + app.js + style.css + vendor/ (copied from web/) + demo.js + demo/{data.json, scenes/, img/}
"""
import hashlib, json, os, shutil, subprocess, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = os.environ.get("API", "localhost:8000")
OUT = sys.argv[1] if len(sys.argv) > 1 else f"{ROOT}/site"
N_SAMPLES = 6  # the UI shows the first six


def curl(*args):
    return subprocess.run(["curl", "-s", "-m", "120", *args], capture_output=True, text=True, check=True).stdout


shutil.rmtree(OUT, ignore_errors=True)
for d in ("demo/scenes", "demo/img"):
    os.makedirs(f"{OUT}/{d}")
for f in ("index.html", "app.js", "style.css"):
    shutil.copy(f"{ROOT}/web/{f}", f"{OUT}/{f}")
shutil.copytree(f"{ROOT}/web/vendor", f"{OUT}/vendor")

info = json.loads(curl(f"{API}/api/info"))
samples = json.loads(curl(f"{API}/api/samples"))[:N_SAMPLES]
results, used = {}, set()
for s in samples:
    name = os.path.basename(s)
    src = f"{ROOT}/data/scenes/{name}"
    shutil.copy(src, f"{OUT}/demo/scenes/{name}")  # byte-identical: the shim identifies a photo by the hash of its bytes
    key = hashlib.sha1(open(src, "rb").read()).hexdigest()
    results[key] = {}
    for ext in ("true", "false"):
        d = json.loads(curl("-F", f"file=@{src}", f"{API}/api/search?extended={ext}"))
        for it in d["items"]:
            for m in it["matches"]:
                used.add((m["source"], m["id"]))
                m["image"] = f"demo/img/{m['id']}.jpg"
        results[key]["ext" if ext == "true" else "base"] = d

for source, pid in sorted(used):  # product photos, shrunk: the UI shows them at most about 400 px wide
    p = f"{ROOT}/data/{'extended/img' if source == 'extended' else 'catalog'}/{pid}.jpg"
    im = Image.open(p).convert("RGB")
    im.thumbnail((640, 640))
    im.save(f"{OUT}/demo/img/{pid}.jpg", quality=82, optimize=True)

json.dump({"info": info, "samples": [f"demo/scenes/{os.path.basename(s)}" for s in samples], "results": results},
          open(f"{OUT}/demo/data.json", "w"), separators=(",", ":"))

# the shim: answers /api/* from demo/data.json; everything else goes to the network as usual
open(f"{OUT}/demo.js", "w").write(r"""/* Static demo shim (generated by app/build_demo_site.py): answers the UI's API calls from recorded results. */
(() => {
  const realFetch = window.fetch.bind(window);
  const data = realFetch("demo/data.json").then((r) => r.json());
  const reply = (obj, status = 200) => new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json" } });
  const sha1 = async (blob) => [...new Uint8Array(await crypto.subtle.digest("SHA-1", await blob.arrayBuffer()))].map((b) => b.toString(16).padStart(2, "0")).join("");
  window.fetch = async (input, init) => {
    const url = typeof input === "string" ? input : input.url;
    if (url.startsWith("/api/info")) return reply((await data).info);
    if (url.startsWith("/api/samples")) return reply((await data).samples);
    if (url.startsWith("/api/search")) {
      const hit = (await data).results[await sha1(init.body.get("file"))];
      if (!hit) return reply({ detail: "This hosted demo only includes the six sample photos. To try your own photo, run the app locally (see the README)." }, 400);
      return reply(url.includes("extended=false") ? hit.base : hit.ext);
    }
    return realFetch(input, init);
  };
  addEventListener("DOMContentLoaded", () => {
    const n = document.createElement("div");
    n.setAttribute("role", "note");
    n.style.cssText = "font:500 13px/1.4 system-ui,sans-serif;padding:8px 16px;text-align:center;background:#111;color:#fff";
    n.innerHTML = 'Static demo: the six sample photos use results recorded from the real app. Your own photos need the backend: <a style="color:#fff" href="live.html">open the live app</a> (online only while its owner's computer is on). <a style="color:#fff" href="https://github.com/uplsiddharth-byte/Shop-the-Look-Visual-Product-Discovery">Source, setup and technical document</a>. Photos belong to their owners and are shown only to demonstrate the software.';
    document.body.prepend(n);
  });
})();
""")

html = open(f"{OUT}/index.html").read()
assert '<script src="app.js" defer></script>' in html, "web/index.html changed: update the demo script injection"
open(f"{OUT}/index.html", "w").write(html.replace('<script src="app.js" defer></script>', '<script src="demo.js"></script>\n  <script src="app.js" defer></script>'))
# demo-only wording and a blank favicon (avoids a 404 in the console); web/ itself is not modified
js = open(f"{OUT}/app.js").read()
assert "We could not read that photo" in js, "web/app.js changed: update the demo heading patch"
open(f"{OUT}/app.js", "w").write(js.replace("We could not read that photo", "That photo is not part of this demo"))
html = open(f"{OUT}/index.html").read()
html = html.replace("<head>", '<head>\n  <link rel="icon" href="data:,">', 1)
html = html.replace('href="/"', 'href="./"')  # the logo link must stay inside the project page (it is served from /<repo>/, not from the domain root)
open(f"{OUT}/index.html", "w").write(html)
open(f"{OUT}/.nojekyll", "w").close()
size = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(OUT) for f in fs)
print(f"site built in {OUT}: {len(samples)} samples, {len(used)} product photos, {size/1048576:.1f} MB")
